---
- hosts: bsv-fq-test01
  remote_user: finadm
  become: yes
  become_method: sudo
  vars:
    # SKTelink Server-socket configure
    - SKT_HOST: 211.237.69.19 # SKTelink Host 211.237.69.19
    - SKT_PORT: 7203 # Normal: 7203
    - CMP_ID: FINNQ1802A # DEV: FINNQ31704, STG: FINNQ1802A, PRD: FINNQ11704
    - AUTH_SEQ: 1802 # DEV: 1708, STG: 1802, PRD: 1708
    # Database configure
    - DB_KIND: 2 # mysql: 2, oracle: 1
    - DB_HOST: 172.27.123.17
    - DB_PORT: 4306
    - DB_NAME: ssmsdb
    - DB_SID: smscon
    - DB_PASS: finnqQ1!
    - DB_TBL_NAME: tbl_submit_queue_sms

  roles:
    - SKTelink-sms
