---
- hosts: bsv-fq-pibap01
  remote_user: finadm
  become: yes
  become_method: sudo

  roles:
    - netbackup-agent
    - zabbix 
    - jdk1.8
    - ipa-client
    - tomcat
    - petra-tobe
    - nfilter 
