---
- hosts: bdv-fq-spdsv01
  remote_user: finadm
  become: yes
  become_method: sudo

  vars_files: 
    - inventories/dev/group_vars/spdsv_tomcat_datasource.yml
    - inventories/dev/host_vars/bdv-fq-spdsv01.yml

  roles:
    #- netbackup-agent
    #- zabbix
    #- jdk1.8
    #- ipa-client
    - tomcat
    - tomcat-datasource
