---
- hosts: bdv-fq-kkoap01
  remote_user: finadm
  become: yes
  become_method: sudo

  vars_files: 
    - inventories/common/group_vars/passwd-vars.yml
    - inventories/dev/host_vars/bdv-fq-kkoap01.yml

  roles:
    - passwd-root.finadm
    - netbackup-agent
    - zabbix 
    - jdk1.8
    - ipa-client
    - tomcat
    - fusioninventory-agent
