---
- hosts: all
  remote_user: finadm
  become: yes
  become_method: sudo

  vars_files:
    - roles/jboss-ews/role-vars/common.var
    - roles/jboss-ews/role-vars/instance.var
  
  roles:
    - jboss-ews/config-ssl