---
- hosts: bpv-fq-apmsv01
  remote_user: finadm
  become: yes
  become_method: sudo

  vars_files: 
    - inventories/common/group_vars/passwd-vars.yml

  roles:
    - passwd-root.finadm
    - jdk1.8
    - netbackup-agent
    - zabbix
    - ipa-client
    - fusioninventory-agent    
