---
- hosts: bdv-fq-fiaap01
  remote_user: finadm
  become: yes
  become_method: sudo

  vars_files:
    - roles/jboss-ews/role-vars/common.var
    - inventories/dev/group_vars/fiaap_jboss-ews_vars.yml
  vars:
    # bind IP address, default : eth0 IP
    - BIND_ADDR:

  roles:
    - { role: jboss-ews/install-engine , when: useInstallEngine == True }
    - { role: jboss-ews/create-instance, when: useInstance == True }
    - { role: jboss-ews/config-mod_cluster, when: useModcluster == True and useModjk == False }
    - { role: jboss-ews/config-mod_jk, when: useModjk == True and useModcluster == False }
    - { role: jboss-ews/config-ssl, when: useSSL == True }
