---
- name: VM provisioning
  hosts: localhost
  vars_prompt:
    - name: "vcpasswd"
      prompt: "Enter vcenter password"
      private: yes
  vars_files: 
    - inventories/common/group_vars/vcenter_info.yml 
    - inventories/stg/host_vars/bsv-fq-mciap01.yml 
  roles: 
    - vm-provisioning

