---
# USAGE: ansible-playbook vm_provisioning.yml -e @host_vars/[dev|stg|prd]/bdv-fq-SAMPLE.yml
- name: "VM DEPLOY | Deploy VM from template"
  vmware_guest:
    hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcpasswd }}"
    validate_certs: "{{ validate_certs }}"
    folder: FINNQ/vm
    datacenter: "{{ datacenter }}"
    name: "{{ vm_hostname }}"
    state: poweredon
    template: "{{ vm_template }}"
    networks:
    - name: VM Network
      ip: "{{ vm_ip }}"
      netmask: "{{ vm_netmask }}"
      gateway: "{{ vm_gateway }}"
    hardware:
      num_cpus: "{{ vm_cpu }}"
      memory_mb: "{{ vm_mem }}"
    disk:
      - size_gb: 100
        datastore: "{{ vm_disk_datastore }}"
      - size_gb: 80
        datastore: "{{ vm_disk_datastore }}"
    esxi_hostname: "{{ vm_esxi }}"

- name: "RECONFIGURE | Re-configure VM HW values"
  vsphere_guest:
    vcenter_hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcpasswd }}"
    guest: "{{ vm_hostname }}"
    validate_certs: "{{ validate_certs }}"
    state: reconfigured
    vm_nic:
      nic1:
        type: vmxnet3
        network: "{{vm_vswitch}}"
        network_type: standard
    esxi:
      datacenter: "{{ datacenter }}"

- name: "[DEV]Add hostname /sw/ansible/hosts after VM Provisioning"
  lineinfile:
    path: /sw/ansible/hosts
    state: present
    insertafter: '\[dev-linux\]'
    line: "{{ vm_hostname }} ansible_port=22 ansible_user=finadm"
  when:
    - vm_hostname | search("^bdv")

- name: "[STG]Add hostname /sw/ansible/hosts after VM Provisioning"
  lineinfile:
    path: /sw/ansible/hosts
    state: present
    insertafter: '\[stg-linux\]' 
    line: "{{ vm_hostname }} ansible_port=22 ansible_user=finadm"
  when:
    - vm_hostname | search("^bsv")

- name: "[PRD]Add hostname /sw/ansible/hosts after VM Provisioning"
  lineinfile:
    path: /sw/ansible/hosts
    state: present
    insertafter: '\[prd-linux\]'
    line: "{{ vm_hostname }}"
  when:
    - vm_hostname | search("^bpv")

- name: "awx inventory update /sw/ansible/hosts"
  shell: sudo -u awx /opt/awx/bin/awx-manage inventory_import --source /sw/ansible/hosts --inventory-name ansible_hosts --overwrite --overwrite-vars

- name: "{{ vm_hostname }} 정방향DNS 등록" 
  ipa_dnsrecord:
    ipa_host: ipasv01.finnq.com
    ipa_pass: "{{ ipa_pass }}"
    state: present
    zone_name: finnq.com.
    record_name: "{{ vm_hostname }}"
    record_type: 'A'
    record_value: "{{ vm_ip }}"
    validate_certs: False

- pause:
    minutes: 1

- name: "{{ vm_hostname }} 서버 /etc/ssh/sshd_config change If PRD-server"
  command: sudo -u awx ansible {{ vm_hostname }} --become-user finadm -m command -a "sudo sed -i 's/Port 22/Port 2222/g' /etc/ssh/sshd_config" -e ansible_ssh_port=22
  when:
    - vm_hostname | search("^bpv")
  ignore_errors: true
  notify: "SSHD restart"

- name: "{{ vm_hostname }} 서버에 infra 관리자 ssh_key 삭제 | 운영서버일 경우 /home/finadm/.ssh/authorized_keys"
  command: sudo -u awx ansible {{ vm_hostname }} --become-user finadm -m shell -a "sudo echo '{{ infra_sshkey }}' > /home/finadm/.ssh/authorized_keys" -e ansible_ssh_port=22
  when:
    - vm_hostname | search("^bpv")
  ignore_errors: true

