---
#- include_role:
#  name: jdk1.7

- name: add group "sol"
  group: name=sol gid=1100 state=present
  
- name: add user "smsadm"
  user: name=smsadm group=sol uid=1102 state=present shell=/bin/bash home=/home/smsadm createhome=yes

- name: make sms directory
  file:
    path: /sw/SKTelink/sms
    state: directory
    group: sol
    owner: smsadm

- name: Extract sms.tar from files
  unarchive: 
    src: sms.tar
    dest: /sw/SKTelink/sms
    owner: smsadm
    group: sol

- name: make sms logs directory
  file:
    path: /logs/SKTelink/sms
    state: directory
    group: sol
    owner: smsadm

- name: Configure cofig.cfg
  template:
    src: config.cfg.j2
    dest: /sw/SKTelink/sms/conf/unix/config.cfg
    owner: smsadm
    group: sol

- name: copy sms.service
  copy:
    src: "{{ item }}"
    dest: /usr/lib/systemd/system/{{ item }}
    mode: 0644
  with_items:
    - sms.service

- name: register service file to systemd
  systemd: daemon_reload=yes

- name: make sure the sms service is running
  systemd: name=sms state=restarted

- name: enable service sms and ensure it
  systemd: name=sms enabled=yes
