---
- hosts: localhost 
  tasks: 
  - name: history timestamp add
    lineinfile:
      path: /etc/profile
      line: '{{ item }}'
    with_items:
      - '# history timestamp add (2018.01.26)'
      - 'HISTTIMEFORMAT="%Y-%m-%d_%H:%M:%S "'
      - 'export HISTTIMEFORMAT'
    become: True
