---
- hosts: prd-linux
  remote_user: finadm
  tasks:
  - name: "/var/spool/cron/root > 1 * * * * /usr/sbin/ntpdate -s 172.27.105.221"
    lineinfile:
      dest: /var/spool/cron/root
      state: present
      regexp: '172.27.105.221'
      line: '1 * * * * /usr/sbin/ntpdate -s 172.27.105.221'
    become: True
    when:
      - (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")
      - ansible_distribution_major_version == "7"

  - name: "/var/spool/cron/root > 1 * * * * /usr/sbin/ntpdate -s 172.27.105.221"
    lineinfile:
      dest: /var/spool/cron/root
      state: present
      regexp: '172.27.105.221'
      line: '1 * * * * /usr/sbin/ntpdate -s 172.27.105.221'
    become: True
    when:
      - (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")
      - ansible_distribution_major_version == "6" and ansible_hostname | search("^bpp") == 0

  - name: "/var/spool/cron/root > 1 * * * * /usr/sbin/ntpdate -s 172.27.105.221"
    lineinfile:
      dest: /var/spool/cron/root
      state: present
      regexp: '172.27.105.221'
      line: '1 * * * * /usr/sbin/ntpdate -s 172.27.105.221; clock -w'
    become: True
    when:
      - (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")
      - ansible_distribution_major_version == "6" and ansible_hostname | search("^bpp") == 1
