---
- hosts: dev-linux, stg-linux, prd-linux
  remote_user: finadm
  vars:
    hostname: "{{ ansible_hostname }}"
    date: "{{ ansible_date_time.date }}"

  tasks:
  - name: "/etc/resolv.conf Check"
    shell: cat /etc/resolv.conf  |grep nameserver|awk '{print $2}'
    register: name_server
    become: True

  - name: "nameserver 목록 파일 기록"
    lineinfile:
      path: "{{ '/tmp/' + hostname + '_nameserver_list' + '.txt' }}"
      state: present
      create: yes
      line: "{{ (hostname + '\t' + item) }}"
    become: True
    with_items: "{{ name_server.stdout_lines }}"

  - name: "nameserver 목록 파일 취합"
    fetch:
      src: "{{ '/tmp/' + hostname + '_nameserver_list' + '.txt' }}"
      dest: "{{ '/tmp/nameserver_list/' + hostname + '_nameserver_list' + '.txt' }}"
      flat: yes
    become: True

- hosts: localhost
  remote_user: finadm
  tasks:
    - name: "서버별 nameserver 목록 병합"
      shell: 'find /tmp/nameserver_list/ -type f -name *.txt -exec cat {} >> /tmp/nameserver_list/nameserver_list.csv \;'
      become: True 
