---
# file: inventories/dev/group_vars/apiap_mod_cluster.yml

# server.xml
onModcluster: True
proxyList: 223.39.114.118:6666
balancer: balancer_dpib
loadBalancingGroup: G_dpib

# setmodenv.sh
httpd_main_hosts: '"223.39.114.118:443"'
onModJk: False
httpd_hosts:
lb_worker: dpib
ajp_port: 8009
http_port: 8080
context_name: /health_check.html

# startup.sh
onKHANagent: False
