---
- name: Deliver configuration template file
  template:
    src: khan-agent.conf
    dest: "{{ install_dir }}/khan-agent/khan-agent-{{ instance_id }}.conf"
    owner: "{{ install_user }}"
    group: "{{ install_group }}"
    mode: 0640
