- name: make directory /apps/jboss/ows/ows.war/raon/transkey_mobile/
  file:
    path: /apps/jboss/ows/ows.war/raon/transkey_mobile/
    state: directory
    owner: jboss
    group: was

- name: Extract keyboard.tar.gz from files
  unarchive: 
    src: keyboard.tar.gz
    dest: /apps/jboss/ows/ows.war/raon/transkey_mobile/
    owner: jboss
    group: was

- name: Extract mobileDemo.tar.gz from files
  unarchive: 
    src: mobileDemo.tar.gz
    dest: /apps/jboss/ows/ows.war/raon/transkey_mobile/
    owner: jboss
    group: was

- name: Extract raon.tar.gz from files
  unarchive: 
    src: raon.tar.gz
    dest: /apps/jboss/ows/ows.war/WEB-INF/
    owner: jboss
    group: was

- name: Extract transkey-4-6-10_17_20180524_X.jar from files
  copy: 
    src: transkey-4-6-10_17_20180524_X.jar
    dest: /apps/jboss/ows/ows.war/WEB-INF/lib
    owner: jboss
    group: was
