---
- hosts: bdv-fq-cbsap01
  remote_user: finadm
  vars_prompt:
    - name: "developer_name"
      prompt: "Enter the developer's number(username)"
      private: no
  tasks:
  - name: " Group add or Check if group exists"
    group:
      name: dev
      gid: 9000
    become: true

  - name: "User : {{ developer_name }} create"
    user:
      name: "{{ developer_name }}"
      uid: "{{ developer_name }}" 
      password: "{{ '1q2w3e4R!' | password_hash('sha512') }}"
      group: dev
    when: 
      - developer_name | search("^11")
    become: true

  - name: "User : {{ developer_name }} create"
    user:
      name: "{{ developer_name }}"
      uid: "{{ '9' + developer_name.split('0')[-1][0:] }}"
      password: "{{ '1q2w3e4R!' | password_hash('sha512') }}"
      group: dev
    when:
      - developer_name | search("^90")
    become: true

  - name: " First login : Force password change"
    command: "chage -d 0 {{ developer_name }}"
    become: True
