---
- name: Copy maria JDBC Dirver
  copy: src=mariadb-java-client-2.2.3.jar dest=/sw/tomcat/lib/ group=was mode=0640

- name: Copy oracle JDBC Dirver
  copy: src=ojdbc6-11.2.0.3.jar dest=/sw/tomcat/lib/ group=was mode=0640

- name: Remove tomcat-jdbc jar
  file: path=/sw/tomcat/lib/tomcat-jdbc.jar state=absent

- name: Copy tomcat-jdbc-enc jar
  copy: src=tomcat-jdbc-enc.jar dest=/sw/tomcat/lib/ group=was mode=0640

- name: Copy encrypt.sh
  copy: src=encrypt.sh dest=/sw/tomcat/bin/ group=was mode=0750

- name: Copy context.xml template
  template: src=conf/context.xml dest=/sw/tomcat/conf/ group=was mode=0640
  when: target_instance == "default" 

- name: Copy context.xml template
  template: src=conf/context.xml dest=/sw/tomcat/domains/{{ target_instance }}/conf/ group=was mode=0644
  when: target_instance != "default"

- name: Restart tomcat 
  systemd: name=tomcat state=restarted
  when: target_instance == "default"

- name: Restart tomcat 
  systemd: name=tomcat-{{target_instance}} state=restarted
  when: target_instance != "default"
