---
- hosts: all
  remote_user: finadm
  tasks:
  - name: Agent Remote Command Enable
    lineinfile:
      dest: /etc/zabbix/zabbix_agentd.conf
      state: present
      regexp: '^# EnableRemoteCommands=0'
      line: 'EnableRemoteCommands=1'
    become: True
#    when:
#      - (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")
#      - ansible_distribution_major_version == "6"
  - name: Zabbix Agent restart
    service:
      name: zabbix-agent
      enabled: True
      state: restarted
    become: True  
#    when:
#      - (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")
#      - ansible_distribution_major_version == "6"
